name: IUTeamsSialim
version: '${project.version}'
main: me.sialim.iuteamssialim.IUTeamsSialim
api-version: '1.20'
commands:
  party:
    usage: "/party <create|invite|leave>"
    aliases:
      - p
  team:
    usage: "/team join <red|blue>"